services:
  - type: web
    name: world-of-tranquility
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: ""
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000
